Dataset:
  name: Physionet
  num_classes: 4
  EEGchannels: 64
  samples: 640

Training:
  batch_size: 504
  batch_size_Conformer: 252
  n_epochs: 1000
  lr: 0.001 
  b1: 0.5 
  b2: 0.999
  b1_2: 0.5 # for CLTNet and others

Augmentation:
  num_augments: 1
  n_segments: 8
  segment_length: 80

CLT:  #CLT
  Model_hyperparams:
    F1: 13
    D: 4
    input_size: 52  #13*4
    hidden_size: 60
    EEGChans: ${Dataset.EEGchannels}
    EEGSamples: ${Dataset.samples} 
    Conv_drop: 0.25 
    numheads: 4
    depth: 6
    num_classes: ${Dataset.num_classes}
  Optimizer_hyperparams:
    Conv_Decay: 0.001 
    Linear_Decay: 0.001   
    Other_Decay: 0.0 

EEGNet:
  Model_hyperparams:
    F1: 8
    D: 2
    drop_out: 0.25
    EEGChans: ${Dataset.EEGchannels}
    EEGSamples: ${Dataset.samples} 
    num_cls: ${Dataset.num_classes}

EEGConformer:
  Model_hyperparams:
    input_dim: 1480
    emb_size: 40
    depth: 6
    n_classes: ${Dataset.num_classes}
    EEGChans: ${Dataset.EEGchannels}
    Physionet: True

CTNet:
  Model_hyperparams:
    heads: 2
    emb_size: 16
    depth: 6
    database_type: 'P'
    eeg1_f1: 8
    eeg1_kernel_size: 64
    eeg1_D: 2
    eeg1_pooling_size1: 8
    eeg1_pooling_size2: 8
    eeg1_dropout_rate: 0.25
    eeg1_number_channel: ${Dataset.EEGchannels}    
    flatten_eeg1: 160

CLTNet:
  Model_hyperparams:
    heads: 2
    emb_size: 16
    depth: 6
    database_type: 'P'
    eeg1_f1: 8
    eeg1_kernel_size: 64
    eeg1_D: 2
    eeg1_pooling_size1: 8
    eeg1_pooling_size2: 8
    eeg1_dropout_rate: 0.25
    eeg1_number_channel: ${Dataset.EEGchannels}
    flatten_eeg1: 160 
